import { Camera, FileText, Route } from 'lucide-react';
import { MoneyCragNode, MoneyNote } from '../../../types/money';
import { flattenBoulders, flattenProblems, problemMeta } from './model';
import { DEV, T } from './theme';

export function ContentView({ view, root, trails, notes, mobile, openBoulder, selectTrail, onOpenComposer }: { view: string; root: MoneyCragNode | null; trails: MoneyCragNode[]; notes: MoneyNote[]; mobile: boolean; openBoulder: (id: string) => void; selectTrail: (id: string) => void; onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void }) {
  return <main style={{ flex: 1, minWidth: 0, overflowY: 'auto', background: T.app }}><div style={{ maxWidth: 1080, margin: '0 auto', padding: mobile ? '20px 18px 90px' : '28px 32px 60px' }}>{view === 'problems' && <Problems root={root} openBoulder={openBoulder} />}{view === 'boulders' && <Boulders root={root} openBoulder={openBoulder} />}{view === 'trails' && <Trails trails={trails} selectTrail={selectTrail} />}{view === 'photos' && <Photos notes={notes} onOpenComposer={onOpenComposer} />}{view === 'notes' && <Notes notes={notes} onOpenComposer={onOpenComposer} />}</div></main>;
}
function Head({ title, sub, action }: { title: string; sub?: string; action?: React.ReactNode }) { return <div style={{ display: 'flex', alignItems: 'flex-end', marginBottom: 20, gap: 12, flexWrap: 'wrap' }}><div><h1 style={{ margin: 0, fontSize: 26, fontWeight: 800, letterSpacing: -0.6, color: T.ink }}>{title}</h1>{sub && <div style={{ fontSize: 13, color: T.mut, marginTop: 4 }}>{sub}</div>}</div>{action && <div style={{ marginLeft: 'auto' }}>{action}</div>}</div>; }
const card: React.CSSProperties = { background: T.surf, border: `1px solid ${T.line}`, borderRadius: 14 };
function Problems({ root, openBoulder }: { root: MoneyCragNode | null; openBoulder: (id: string) => void }) { const all = flattenProblems(root); return <><Head title="Problems" sub={`${all.length} lines across every area.`} /><div style={{ ...card, overflow: 'hidden' }}>{all.map((p, i) => { const meta = problemMeta(p.feature); return <div key={p.feature.id} onClick={() => openBoulder(p.boulder.feature.id)} style={{ display: 'grid', gridTemplateColumns: '64px 1fr 150px 150px 104px', gap: 12, alignItems: 'center', padding: '11px 16px', borderTop: i ? `1px solid ${T.line}` : 'none', cursor: 'pointer' }}><span style={{ fontFamily: T.mono, fontSize: 13, fontWeight: 700, color: T.accent }}>{meta.grade}</span><span style={{ fontSize: 14, fontWeight: 600, color: T.ink }}>{p.feature.title}</span><span style={{ fontSize: 12.5, color: T.mut }}>{p.boulder.feature.title}</span><span style={{ fontSize: 12.5, color: T.mut }}>{p.area.feature.title}</span><Badge status={meta.status} /></div>; })}</div></>; }
function Boulders({ root, openBoulder }: { root: MoneyCragNode | null; openBoulder: (id: string) => void }) { const list = flattenBoulders(root); return <><Head title="Boulders" sub={`${list.length} blocks — tracked from scouted to established.`} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(280px,1fr))', gap: 14 }}>{list.map(b => { const dev = b.feature.status as keyof typeof DEV.meta; const m = DEV.meta[dev] ?? DEV.meta.scouted; return <div key={b.feature.id} onClick={() => openBoulder(b.feature.id)} style={{ ...card, overflow: 'hidden', cursor: 'pointer' }}><Stripe label={`${b.feature.title.toLowerCase()} · topo`} ratio="16 / 8" /><div style={{ padding: 14 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}><span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, color: m.c, background: m.bg, padding: '2px 8px', borderRadius: 5 }}>{m.short}</span><span style={{ marginLeft: 'auto', fontFamily: T.mono, fontSize: 11, color: T.mut }}>{b.problems.length} problems</span></div><div style={{ fontSize: 16, fontWeight: 800, color: T.ink }}>{b.feature.title}</div></div></div>; })}</div></>; }
function Trails({ trails, selectTrail }: { trails: MoneyCragNode[]; selectTrail: (id: string) => void }) { return <><Head title="Trails" sub="Approaches and connectors between areas — GPX or hand-drawn." /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(260px,1fr))', gap: 14 }}>{trails.map(tr => <div key={tr.feature.id} onClick={() => selectTrail(tr.feature.id)} style={{ ...card, padding: 16, cursor: 'pointer' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}><Route color={T.accent} /><div style={{ flex: 1 }}><div style={{ fontSize: 15, fontWeight: 700, color: T.ink }}>{tr.feature.title}</div><div style={{ fontFamily: T.mono, fontSize: 11, color: T.mut }}>{String(tr.feature.properties.dist ?? '—')} · {String(tr.feature.properties.gain ?? '—')}</div></div></div></div>)}</div></>; }
function Photos({ notes, onOpenComposer }: { notes: MoneyNote[]; onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void }) { const blocks = notes.flatMap(n => (n.blocks ?? []).filter(b => b.kind === 'photo' || b.kind === 'sketch')); return <><Head title="Photos" sub={`${blocks.length} uploaded · topos, sketches, conditions`} action={<button onClick={() => onOpenComposer('photo')} style={btnA}><Camera size={15} />Add photo</button>} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))', gap: 12 }}>{blocks.map((b, i) => b.url ? <img key={i} src={b.url} alt="" style={{ width: '100%', aspectRatio: '4 / 3', objectFit: 'cover', borderRadius: 8, border: `1px solid ${T.line}` }} /> : <Stripe key={i} label={b.name ?? b.kind} />)}{['overview topo', 'approach', 'conditions', 'panorama'].map(l => <Stripe key={l} label={l} />)}</div></>; }
function Notes({ notes, onOpenComposer }: { notes: MoneyNote[]; onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void }) { return <><Head title="Notes" sub="Everything logged — beta, conditions, decisions, access." action={<button onClick={() => onOpenComposer(null)} style={btnA}><FileText size={15} />New note</button>} /><div style={{ maxWidth: 680 }}>{notes.map(n => <div key={n.id} style={{ ...card, padding: 16, marginBottom: 12 }}><div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 8 }}><span style={{ width: 24, height: 24, borderRadius: '50%', background: T.av, color: '#fff', fontSize: 10, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>MC</span><span style={{ fontSize: 13, fontWeight: 700, color: T.ink }}>Team</span><span style={{ marginLeft: 'auto', fontFamily: T.mono, fontSize: 11, color: T.mut }}>{new Date(n.created_at).toLocaleDateString()}</span></div><p style={{ margin: '0 0 8px', fontSize: 13.5, lineHeight: 1.55, color: '#D9CBBD' }}>{n.body}</p>{(n.tags ?? []).length > 0 && <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>{(n.tags ?? []).map(t => <span key={t} style={{ fontSize: 10.5, color: T.mut, background: T.surf2, border: `1px solid ${T.line}`, borderRadius: 20, padding: '2px 8px' }}>#{t}</span>)}</div>}</div>)}</div></>; }
function Stripe({ label, ratio }: { label: string; ratio?: string }) { return <div style={{ width: '100%', aspectRatio: ratio || '4 / 3', backgroundColor: T.map.slot, backgroundImage: `repeating-linear-gradient(45deg, ${T.map.slotStripe} 0 1px, transparent 1px 9px)`, display: 'flex', alignItems: 'flex-end', overflow: 'hidden', borderRadius: 8 }}><span style={{ fontFamily: T.mono, fontSize: 10, color: T.map.slotText, padding: '5px 7px' }}>{label}</span></div>; }
function Badge({ status }: { status: string }) { const c = status === 'sent' ? T.blue : status === 'project' ? T.accent : T.mut; return <span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: c, background: `${c}22`, padding: '2px 7px', borderRadius: 5 }}>{status}</span>; }
const btnA: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 7, border: 'none', borderRadius: 9, padding: '10px 15px', background: T.accent, color: T.onAccent, fontWeight: 700, fontSize: 13, cursor: 'pointer' };
