import { useMemo, useState } from 'react';
import { Camera, FileText, RotateCcw, Route } from 'lucide-react';
import { MoneyCragNode, MoneyNote, MoneyTrashItem, MoneyUpload } from '../../../types/money';
import { cragProblems, findNode, flattenBoulders, flattenProblems, pathTo, problemMeta } from './model';
import { DEV, T } from './theme';
import { PhotoLightbox, PhotoLightboxItem, UploadPhotoButton } from './PhotoLightbox';

type OpenPhoto = (item: PhotoLightboxItem) => void;

interface ContentViewProps {
  view: string;
  root: MoneyCragNode | null;
  trails: MoneyCragNode[];
  notes: MoneyNote[];
  uploads: MoneyUpload[];
  trash: MoneyTrashItem[];
  canWrite: boolean;
  mobile: boolean;
  openBoulder: (id: string) => void;
  selectTrail: (id: string) => void;
  onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void;
  onEditNote: (note: MoneyNote) => void;
  onDeleteNote: (note: MoneyNote) => void;
  onDeleteUpload: (upload: MoneyUpload) => void;
  onRestore: (id: string) => void;
}

export function ContentView({ view, root, trails, notes, uploads, trash, canWrite, mobile, openBoulder, selectTrail, onOpenComposer, onEditNote, onDeleteNote, onDeleteUpload, onRestore }: ContentViewProps) {
  const [selectedPhoto, setSelectedPhoto] = useState<PhotoLightboxItem | null>(null);
  return <main style={{ flex: 1, minWidth: 0, overflowY: 'auto', background: T.app }}>
    <div style={{ maxWidth: 1080, margin: '0 auto', padding: mobile ? '20px 18px 90px' : '28px 32px 60px' }}>
      {view === 'problems' && <Problems root={root} openBoulder={openBoulder} />}
      {view === 'boulders' && <Boulders root={root} openBoulder={openBoulder} />}
      {view === 'trails' && <Trails trails={trails} selectTrail={selectTrail} />}
      {view === 'photos' && <Photos root={root} notes={notes} uploads={uploads} canWrite={canWrite} onOpenComposer={onOpenComposer} onOpenPhoto={setSelectedPhoto} onDeleteUpload={onDeleteUpload} />}
      {view === 'notes' && <Notes root={root} notes={notes} uploads={uploads} canWrite={canWrite} onOpenComposer={onOpenComposer} onOpenPhoto={setSelectedPhoto} onEditNote={onEditNote} onDeleteNote={onDeleteNote} onDeleteUpload={onDeleteUpload} />}
      {view === 'trash' && <Trash items={trash} canWrite={canWrite} onRestore={onRestore} />}
    </div>
    {selectedPhoto && <PhotoLightbox item={selectedPhoto} canDelete={canWrite} onDelete={upload => { onDeleteUpload(upload); setSelectedPhoto(null); }} onClose={() => setSelectedPhoto(null)} />}
  </main>;
}

function Head({ title, sub, action }: { title: string; sub?: string; action?: React.ReactNode }) { return <div style={{ display: 'flex', alignItems: 'flex-end', marginBottom: 20, gap: 12, flexWrap: 'wrap' }}><div><h1 style={{ margin: 0, fontSize: 26, fontWeight: 800, letterSpacing: -0.6, color: T.ink }}>{title}</h1>{sub && <div style={{ fontSize: 13, color: T.mut, marginTop: 4 }}>{sub}</div>}</div>{action && <div style={{ marginLeft: 'auto' }}>{action}</div>}</div>; }
const card: React.CSSProperties = { background: T.surf, border: `1px solid ${T.line}`, borderRadius: 14 };
const miniBtn: React.CSSProperties = { border: `1px solid ${T.line2}`, background: T.inset, color: T.mut, borderRadius: 6, cursor: 'pointer', fontSize: 10.5, padding: '3px 6px', fontWeight: 800 };

function Problems({ root, openBoulder }: { root: MoneyCragNode | null; openBoulder: (id: string) => void }) { const all = flattenProblems(root); return <><Head title="Problems" sub={`${all.length} lines across every area.`} /><div style={{ ...card, overflow: 'hidden' }}>{all.map((p, i) => { const meta = problemMeta(p.feature); return <div key={p.feature.id} onClick={() => openBoulder(p.boulder.feature.id)} style={{ display: 'grid', gridTemplateColumns: '64px 1fr 150px 150px 104px', gap: 12, alignItems: 'center', padding: '11px 16px', borderTop: i ? `1px solid ${T.line}` : 'none', cursor: 'pointer' }}><span style={{ fontFamily: T.mono, fontSize: 13, fontWeight: 700, color: T.accent }}>{meta.grade}</span><span style={{ fontSize: 14, fontWeight: 600, color: T.ink }}>{p.feature.title}</span><span style={{ fontSize: 12.5, color: T.mut }}>{p.boulder.feature.title}</span><span style={{ fontSize: 12.5, color: T.mut }}>{p.area.feature.title}</span><Badge status={meta.status} /></div>; })}</div></>; }
function Boulders({ root, openBoulder }: { root: MoneyCragNode | null; openBoulder: (id: string) => void }) { const list = flattenBoulders(root); return <><Head title="Boulders" sub={`${list.length} blocks — tracked from scouted to established.`} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(280px,1fr))', gap: 14 }}>{list.map(b => { const dev = b.feature.status as keyof typeof DEV.meta; const m = DEV.meta[dev] ?? DEV.meta.scouted; return <div key={b.feature.id} onClick={() => openBoulder(b.feature.id)} style={{ ...card, overflow: 'hidden', cursor: 'pointer' }}><Stripe label={`${b.feature.title.toLowerCase()} · topo`} ratio="16 / 8" /><div style={{ padding: 14 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}><span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, color: m.c, background: m.bg, padding: '2px 8px', borderRadius: 5 }}>{m.short}</span><span style={{ marginLeft: 'auto', fontFamily: T.mono, fontSize: 11, color: T.mut }}>{cragProblems(b).length} problems</span></div><div style={{ fontSize: 16, fontWeight: 800, color: T.ink }}>{b.feature.title}</div></div></div>; })}</div></>; }
function Trails({ trails, selectTrail }: { trails: MoneyCragNode[]; selectTrail: (id: string) => void }) { return <><Head title="Trails" sub="Approaches and connectors between areas — GPX or hand-drawn." /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(260px,1fr))', gap: 14 }}>{trails.map(tr => <div key={tr.feature.id} onClick={() => selectTrail(tr.feature.id)} style={{ ...card, padding: 16, cursor: 'pointer' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 8 }}><Route color={T.accent} /><div style={{ flex: 1 }}><div style={{ fontSize: 15, fontWeight: 700, color: T.ink }}>{tr.feature.title}</div><div style={{ fontFamily: T.mono, fontSize: 11, color: T.mut }}>{String(tr.feature.properties.dist ?? '—')} · {String(tr.feature.properties.gain ?? '—')}</div></div></div></div>)}</div></>; }
function Photos({ root, notes, uploads, canWrite, onOpenComposer, onOpenPhoto, onDeleteUpload }: { root: MoneyCragNode | null; notes: MoneyNote[]; uploads: MoneyUpload[]; canWrite: boolean; onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void; onOpenPhoto: OpenPhoto; onDeleteUpload: (upload: MoneyUpload) => void }) { const photoItems = useMemo(() => uploads.map(upload => lightboxItemForUpload(upload, notes, root)), [uploads, notes, root]); return <><Head title="Photos" sub={`${uploads.length} uploaded · topos, sketches, conditions`} action={<button onClick={() => onOpenComposer('photo')} style={btnA}><Camera size={15} />Add photo</button>} /><div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(200px,1fr))', gap: 12 }}>{photoItems.map(item => <UploadPhotoButton key={item.upload.id} upload={item.upload} ratio="4 / 3" title={item.title} canDelete={canWrite} onDelete={onDeleteUpload} onOpen={() => onOpenPhoto(item)} />)}{uploads.length === 0 && ['overview topo', 'approach', 'conditions', 'panorama'].map(l => <Stripe key={l} label={l} />)}</div></>; }
function Notes({ root, notes, uploads, canWrite, onOpenComposer, onOpenPhoto, onEditNote, onDeleteNote, onDeleteUpload }: { root: MoneyCragNode | null; notes: MoneyNote[]; uploads: MoneyUpload[]; canWrite: boolean; onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void; onOpenPhoto: OpenPhoto; onEditNote: (note: MoneyNote) => void; onDeleteNote: (note: MoneyNote) => void; onDeleteUpload: (upload: MoneyUpload) => void }) { return <><Head title="Notes" sub="Everything logged — beta, conditions, decisions, access." action={<button onClick={() => onOpenComposer(null)} style={btnA}><FileText size={15} />New note</button>} /><div style={{ maxWidth: 680 }}>{notes.map(n => { const noteUploads = uploadsForNoteBlocks(uploads, n); const contextLabel = contextLabelForFeature(root, n.target_ref ?? n.feature_id); return <div key={n.id} style={{ ...card, padding: 16, marginBottom: 12 }}><div style={{ display: 'flex', alignItems: 'center', gap: 9, marginBottom: 8 }}><span style={{ width: 24, height: 24, borderRadius: '50%', background: T.av, color: '#fff', fontSize: 10, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>MC</span><span style={{ fontSize: 13, fontWeight: 700, color: T.ink }}>Team</span><span style={{ marginLeft: 'auto', fontFamily: T.mono, fontSize: 11, color: T.mut }}>{new Date(n.created_at).toLocaleDateString()}</span>{canWrite && <><button aria-label="Edit note" onClick={() => onEditNote(n)} style={miniBtn}>Edit</button><button aria-label="Delete note" onClick={() => { if (window.confirm('Delete this note?')) onDeleteNote(n); }} style={{ ...miniBtn, color: '#E6A299' }}>Delete</button></>}</div><p style={{ margin: '0 0 8px', fontSize: 13.5, lineHeight: 1.55, color: '#D9CBBD' }}>{n.body}</p>{noteUploads.length > 0 && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(120px,1fr))', gap: 8, marginBottom: 10 }}>{noteUploads.map(upload => <UploadPhotoButton key={upload.id} upload={upload} canDelete={canWrite} onDelete={onDeleteUpload} onOpen={() => onOpenPhoto({ upload, title: upload.original_filename, contextLabel, noteBody: n.body })} />)}</div>}{(n.tags ?? []).length > 0 && <div style={{ display: 'flex', gap: 5, flexWrap: 'wrap' }}>{(n.tags ?? []).map(t => <span key={t} style={{ fontSize: 10.5, color: T.mut, background: T.surf2, border: `1px solid ${T.line}`, borderRadius: 20, padding: '2px 8px' }}>#{t}</span>)}</div>}</div>; })}</div></>; }
function Trash({ items, canWrite, onRestore }: { items: MoneyTrashItem[]; canWrite: boolean; onRestore: (id: string) => void }) { return <><Head title="Trash" sub={`${items.length} deleted area${items.length === 1 ? '' : 's'} ready to restore.`} /><div style={{ ...card, overflow: 'hidden' }}>{items.length === 0 && <div style={{ padding: 18, color: T.mut, fontSize: 13 }}>Trash is empty.</div>}{items.map((item, i) => <div key={item.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '13px 16px', borderTop: i ? `1px solid ${T.line}` : 'none' }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 14, fontWeight: 800, color: T.ink }}>{item.title}</div><div style={{ fontFamily: T.mono, fontSize: 10.5, color: T.mut }}>{item.path.join(' / ')} · {item.descendant_count} descendant{item.descendant_count === 1 ? '' : 's'} · deleted {new Date(item.deleted_at).toLocaleDateString()}</div></div><button disabled={!canWrite} onClick={() => onRestore(item.id)} style={{ display: 'flex', alignItems: 'center', gap: 7, border: `1px solid ${T.accentDim}`, borderRadius: 9, padding: '9px 12px', background: canWrite ? T.accentSoft : 'transparent', color: canWrite ? T.accent : T.faint, fontWeight: 800, cursor: canWrite ? 'pointer' : 'default' }}><RotateCcw size={15} />Restore</button></div>)}</div></>; }
function Stripe({ label, ratio }: { label: string; ratio?: string }) { return <div style={{ width: '100%', aspectRatio: ratio || '4 / 3', backgroundColor: T.map.slot, backgroundImage: `repeating-linear-gradient(45deg, ${T.map.slotStripe} 0 1px, transparent 1px 9px)`, display: 'flex', alignItems: 'flex-end', overflow: 'hidden', borderRadius: 8 }}><span style={{ fontFamily: T.mono, fontSize: 10, color: T.map.slotText, padding: '5px 7px' }}>{label}</span></div>; }
function Badge({ status }: { status: string }) { const c = status === 'sent' ? T.blue : status === 'project' ? T.accent : T.mut; return <span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: c, background: `${c}22`, padding: '2px 7px', borderRadius: 5 }}>{status}</span>; }
const btnA: React.CSSProperties = { display: 'flex', alignItems: 'center', gap: 7, border: 'none', borderRadius: 9, padding: '10px 15px', background: T.accent, color: T.onAccent, fontWeight: 700, fontSize: 13, cursor: 'pointer' };
function uploadsForNoteBlocks(uploads: MoneyUpload[], note: MoneyNote): MoneyUpload[] { const ids = new Set((note.blocks ?? []).map(block => block.upload_id).filter((id): id is string => Boolean(id))); return uploads.filter(upload => ids.has(upload.id) || upload.note_id === note.id); }
function lightboxItemForUpload(upload: MoneyUpload, notes: MoneyNote[], root: MoneyCragNode | null): PhotoLightboxItem { const note = noteForUpload(upload, notes); const featureId = upload.feature_id ?? note?.target_ref ?? note?.feature_id; return { upload, title: upload.original_filename, contextLabel: contextLabelForFeature(root, featureId), noteBody: note?.body }; }
function noteForUpload(upload: MoneyUpload, notes: MoneyNote[]): MoneyNote | undefined { return notes.find(note => note.id === upload.note_id || (note.blocks ?? []).some(block => block.upload_id === upload.id)); }
function contextLabelForFeature(root: MoneyCragNode | null, featureId?: string | null): string | undefined { if (!featureId) return undefined; const path = pathTo(root, featureId); if (path.length > 0) return path.map(node => node.feature.title).join(' / '); const node = findNode(root, featureId); return node?.feature.title; }
