import { useEffect, useMemo, useState } from 'react';
import { Camera, Edit3, FileText, Mountain, Plus, Route, Star, Trash2 } from 'lucide-react';
import { MoneyCragNode, MoneyDevStatus, MoneyNote, MoneyProblemStatus, MoneyTrailCategory, MoneyUpload } from '../../../types/money';
import { DEV, PTYPES, T } from './theme';
import { cragBoulders, cragChildren, cragProblems, flattenAreas, notesFor, problemMeta, stats } from './model';
import { PhotoLightbox, PhotoLightboxItem, UploadPhotoButton } from './PhotoLightbox';

interface Props {
  root: MoneyCragNode | null;
  area: MoneyCragNode;
  selectedBoulder: MoneyCragNode | null;
  selectedTrail: MoneyCragNode | null;
  notes: MoneyNote[];
  uploads: MoneyUpload[];
  tab: string;
  mobile: boolean;
  expanded: boolean;
  canWrite: boolean;
  canEditArea: boolean;
  setExpanded: (v: boolean) => void;
  setTab: (v: string) => void;
  onEnter: (id: string) => void;
  onSelectBoulder: (id: string) => void;
  onNewArea: () => void;
  onNewBoulder: () => void;
  onEditArea: () => void;
  onDeleteArea: () => void;
  onSetDev: (id: string, dev: MoneyDevStatus) => void;
  onAddProblem: (boulderId: string, p: { name: string; grade: string; status: MoneyProblemStatus; stars: number; fa?: string | null; types: string[] }) => void;
  onRenameBoulder: (boulder: MoneyCragNode, title: string) => void;
  onOpenComposer: (kind?: 'photo' | 'sketch' | 'file' | null) => void;
  onEditNote: (note: MoneyNote) => void;
  onDeleteNote: (note: MoneyNote) => void;
  onDeleteUpload: (upload: MoneyUpload) => void;
  onUpdateTrail: (trail: MoneyCragNode, updates: { title: string; category: MoneyTrailCategory; destinationFeatureId?: string | null; destinationLabel?: string | null }) => void;
  onDeleteTrail: (trail: MoneyCragNode) => void;
}

type OpenPhoto = (upload: MoneyUpload, context?: Omit<PhotoLightboxItem, 'upload' | 'title'>) => void;
type InternalProps = Props & { onOpenPhoto: OpenPhoto };

export function DetailPanel(props: Props) {
  const { area, selectedBoulder, selectedTrail, mobile, expanded, setExpanded } = props;
  const [selectedPhoto, setSelectedPhoto] = useState<PhotoLightboxItem | null>(null);
  const onOpenPhoto: OpenPhoto = (upload, context = {}) => setSelectedPhoto({ upload, title: upload.original_filename, ...context });
  const childProps: InternalProps = { ...props, onOpenPhoto };
  const target = selectedTrail ?? selectedBoulder ?? area;
  const sub = selectedTrail ? 'Trail' : selectedBoulder ? `Boulder · ${cragProblems(selectedBoulder).length} problems` : `${String(area.feature.properties.kind ?? 'Boulders')} · ${String(area.feature.properties.aspect ?? '')}`;
  const body = selectedTrail ? <TrailBody {...childProps} trail={selectedTrail} /> : selectedBoulder ? <BoulderBody {...childProps} boulder={selectedBoulder} /> : <AreaBody {...childProps} />;
  const panel = mobile ? <div style={{ position: 'absolute', left: 0, right: 0, bottom: 0, zIndex: 25, background: T.surf, borderTop: `1px solid ${T.line2}`, borderTopLeftRadius: 18, borderTopRightRadius: 18, boxShadow: '0 -10px 40px rgba(0,0,0,0.5)', display: 'flex', flexDirection: 'column', height: expanded ? '76vh' : 'auto', maxHeight: '76vh' }}><div onClick={() => setExpanded(!expanded)} style={{ flexShrink: 0, padding: '8px 18px 10px', cursor: 'pointer' }}><div style={{ width: 36, height: 4, borderRadius: 2, background: T.line2, margin: '0 auto 10px' }} /><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 17, fontWeight: 800, color: T.ink, whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }}>{target.feature.title}</div><div style={{ fontFamily: T.mono, fontSize: 11, color: T.mut }}>{sub}</div></div></div></div>{expanded && body}</div> : <aside style={{ width: 372, flexShrink: 0, background: T.surf, borderLeft: `1px solid ${T.line}`, display: 'flex', flexDirection: 'column', minHeight: 0 }}><div style={{ padding: '18px 20px 12px', flexShrink: 0 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 7 }}><span style={{ width: 10, height: 10, borderRadius: 3, background: selectedTrail ? T.map.trail : T.accent, transform: 'rotate(45deg)' }} /><span style={{ fontFamily: T.mono, fontSize: 11, color: T.mut, letterSpacing: 0.3, textTransform: 'uppercase' }}>{sub}</span></div><h2 style={{ margin: 0, fontSize: 23, fontWeight: 800, letterSpacing: -0.5, color: T.ink }}>{target.feature.title}</h2></div>{body}</aside>;
  return <>{panel}{selectedPhoto && <PhotoLightbox item={selectedPhoto} canDelete={props.canWrite} onDelete={upload => { props.onDeleteUpload(upload); setSelectedPhoto(null); }} onClose={() => setSelectedPhoto(null)} />}</>;
}

function AreaBody(props: InternalProps) {
  const st = stats(props.area);
  const areaNotes = notesFor(props.notes, 'area', props.area.feature.id);
  const children = cragChildren(props.area);
  const boulders = cragBoulders(props.area);
  const areaUploads = uploadsForTarget(props.uploads, areaNotes, props.area.feature.id);
  return <>
    <div style={{ display: 'flex', gap: 2, padding: '0 20px', borderBottom: `1px solid ${T.line}`, flexShrink: 0 }}>{['overview', 'notes', 'photos'].map(k => <button key={k} onClick={() => props.setTab(k)} style={{ padding: '10px 12px', fontSize: 13, fontWeight: props.tab === k ? 700 : 500, color: props.tab === k ? T.ink : T.mut, border: 'none', borderBottom: `2px solid ${props.tab === k ? T.accent : 'transparent'}`, background: 'transparent', cursor: 'pointer', textTransform: 'capitalize' }}>{k}</button>)}</div>
    <div style={scroll}>
      {props.tab === 'overview' && <>
        <p style={p}>{props.area.feature.description}</p>
        {props.canEditArea && <><Label>Area actions</Label><div style={{ display: 'flex', gap: 8, marginBottom: 16 }}><BigButton icon={<Edit3 size={16} />} title="Reshape area" sub="Drag lon/lat boundary vertices" onClick={props.onEditArea} /><BigButton icon={<Trash2 size={16} />} title="Delete area" sub="Move subtree to trash" onClick={props.onDeleteArea} danger /></div></>}
        {props.canWrite && <><Label>Add to {props.area.feature.title}</Label><div style={{ display: 'flex', gap: 8, marginBottom: 16 }}><BigButton icon={<Plus size={16} />} title="Add sub-area" sub="Trace a nested boundary" onClick={props.onNewArea} /><BigButton icon={<Mountain size={16} />} title="Add boulder" sub="Trace a block outline" onClick={props.onNewBoulder} /></div></>}
        <StatGrid items={[[ 'Sub-areas', st.subareas ], [ 'Boulders', st.boulders ], [ 'Problems', st.problems ], [ 'Sent', st.sent ]]} />
        <DevBar st={st} />
        {children.length > 0 && <><Label>Sub-areas</Label><List>{children.map(c => <Row key={c.feature.id} title={c.feature.title} sub={`${cragBoulders(c).length} boulders · ${cragChildren(c).length} sub`} onClick={() => props.onEnter(c.feature.id)} />)}</List></>}
        {boulders.length > 0 && <><Label>Boulders</Label><List>{boulders.map(b => <Row key={b.feature.id} title={b.feature.title} sub={`${cragProblems(b).length} problems`} onClick={() => props.onSelectBoulder(b.feature.id)} right={<DevBadge dev={b.feature.status as MoneyDevStatus} />} />)}</List></>}
      </>}
      {props.tab === 'notes' && <><AddNoteCTA onOpen={props.onOpenComposer} />{areaNotes.map(n => <NoteCard key={n.id} note={n} uploads={props.uploads} contextLabel={props.area.feature.title} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onEdit={props.onEditNote} onDelete={props.onDeleteNote} onDeleteUpload={props.onDeleteUpload} />)}</>}
      {props.tab === 'photos' && <PhotoGrid uploads={areaUploads} contextLabel={props.area.feature.title} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onDeleteUpload={props.onDeleteUpload} />}
    </div>
  </>;
}
function BoulderBody(props: InternalProps & { boulder: MoneyCragNode }) { const [adding, setAdding] = useState(false); const b = props.boulder; const boulderNotes = notesFor(props.notes, 'boulder', b.feature.id); const boulderUploads = uploadsForTarget(props.uploads, boulderNotes, b.feature.id); const problems = cragProblems(b); const contextLabel = `${props.area.feature.title} / ${b.feature.title}`; return <div style={scroll}><BoulderTitleEditor boulder={b} canWrite={props.canWrite} onRenameBoulder={props.onRenameBoulder} /><DevPicker boulder={b} canWrite={props.canWrite} onSetDev={props.onSetDev} /><PhotoGrid uploads={boulderUploads} ratio="3 / 4" contextLabel={contextLabel} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onDeleteUpload={props.onDeleteUpload} />{props.canWrite && <div style={{ display: 'flex', gap: 8, marginBottom: 16 }}><SmallButton onClick={() => setAdding(!adding)}><Plus size={15} />Add problem</SmallButton><SmallButton onClick={() => props.onOpenComposer('sketch')}>Draw topo lines</SmallButton></div>}{adding && <AddProblem onAdd={pr => { props.onAddProblem(b.feature.id, pr); setAdding(false); }} />}<Label>Problems</Label><List>{problems.map((problem, i) => <ProblemRow key={problem.feature.id} p={problem} i={i} />)}{problems.length === 0 && <Empty>No problems yet.</Empty>}</List><div style={{ marginTop: 16 }}><Label>Notes & beta</Label><AddNoteCTA onOpen={props.onOpenComposer} />{boulderNotes.map(n => <NoteCard key={n.id} note={n} uploads={props.uploads} contextLabel={contextLabel} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onEdit={props.onEditNote} onDelete={props.onDeleteNote} onDeleteUpload={props.onDeleteUpload} />)}</div></div>; }
function BoulderTitleEditor({ boulder, canWrite, onRenameBoulder }: { boulder: MoneyCragNode; canWrite: boolean; onRenameBoulder: (boulder: MoneyCragNode, title: string) => void }) { const [title, setTitle] = useState(boulder.feature.title); useEffect(() => setTitle(boulder.feature.title), [boulder.feature.id, boulder.feature.title]); if (!canWrite) return null; const dirty = title.trim() !== boulder.feature.title; return <div style={{ background: T.inset, border: `1px solid ${T.line}`, borderRadius: 10, padding: 12, marginBottom: 14 }}><Label>Boulder name</Label><input aria-label="Boulder name" value={title} onChange={e => setTitle(e.target.value)} maxLength={200} style={inp} /><div style={{ display: 'flex', gap: 8, marginTop: 10 }}><button disabled={!dirty || !title.trim()} onClick={() => onRenameBoulder(boulder, title.trim())} style={{ ...actionBtn, flex: 1, opacity: !dirty || !title.trim() ? 0.45 : 1 }}>Save boulder name</button><button disabled={!dirty} onClick={() => setTitle(boulder.feature.title)} style={{ ...actionBtn, flex: 1, opacity: !dirty ? 0.45 : 1 }}>Reset</button></div></div>; }
const trailCategoryOptions: Array<{ value: MoneyTrailCategory; label: string }> = [
  { value: 'connector', label: 'Connector' },
  { value: 'approach', label: 'Approach' },
  { value: 'trail_to_area', label: 'Trail to area' },
  { value: 'trail_to_destination', label: 'Trail to destination' },
];

function TrailBody(props: InternalProps & { trail: MoneyCragNode | null }) {
  const trail = props.trail;
  if (!trail) return null;
  const trailNotes = notesFor(props.notes, 'trail', trail.feature.id);
  const trailUploads = uploadsForTarget(props.uploads, trailNotes, trail.feature.id);
  const contextLabel = trail.feature.title;
  const areas = flattenAreas(props.root ?? props.area).filter(node => node.feature.id !== props.area.feature.id || node.feature.title);
  const category = normalizeTrailCategory(trail.feature.properties.trail_category);
  const destinationFeatureId = typeof trail.feature.properties.trail_destination_feature_id === 'string' ? trail.feature.properties.trail_destination_feature_id : '';
  const destinationLabel = typeof trail.feature.properties.trail_destination_label === 'string' ? trail.feature.properties.trail_destination_label : '';
  const destinationName = destinationFeatureId ? areas.find(node => node.feature.id === destinationFeatureId)?.feature.title : destinationLabel;
  const [title, setTitle] = useState(trail.feature.title);
  const [draftCategory, setDraftCategory] = useState<MoneyTrailCategory>(category);
  const [draftDestinationId, setDraftDestinationId] = useState(destinationFeatureId);
  const [draftDestinationLabel, setDraftDestinationLabel] = useState(destinationLabel);
  useEffect(() => {
    setTitle(trail.feature.title);
    setDraftCategory(category);
    setDraftDestinationId(destinationFeatureId);
    setDraftDestinationLabel(destinationLabel);
  }, [category, destinationFeatureId, destinationLabel, trail.feature.id, trail.feature.title]);
  const dirty = title.trim() !== trail.feature.title || draftCategory !== category || draftDestinationId !== destinationFeatureId || draftDestinationLabel.trim() !== destinationLabel;
  const needsDestination = draftCategory === 'trail_to_area' || draftCategory === 'trail_to_destination';
  return <div style={scroll}>
    <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}><Route size={18} color={T.accent} /><span style={{ fontFamily: T.mono, fontSize: 11, color: T.mut }}>TRAIL · {String(trail.feature.properties.source ?? 'mapped').toUpperCase()}</span></div>
    {props.canWrite && <div style={{ background: T.inset, border: `1px solid ${T.line}`, borderRadius: 10, padding: 12, marginBottom: 14 }}><Label>Trail management</Label><input aria-label="Trail label" value={title} onChange={e => setTitle(e.target.value)} maxLength={200} style={inp} /><select aria-label="Trail category" value={draftCategory} onChange={e => setDraftCategory(e.target.value as MoneyTrailCategory)} style={{ ...inp, marginTop: 8 }}>{trailCategoryOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}</select>{draftCategory === 'trail_to_area' && <select aria-label="Destination area" value={draftDestinationId} onChange={e => setDraftDestinationId(e.target.value)} style={{ ...inp, marginTop: 8 }}><option value="">Select destination area</option>{areas.map(node => <option key={node.feature.id} value={node.feature.id}>{node.feature.title}</option>)}</select>}{draftCategory === 'trail_to_destination' && <input aria-label="Destination label" value={draftDestinationLabel} onChange={e => setDraftDestinationLabel(e.target.value)} placeholder="Destination name" maxLength={200} style={{ ...inp, marginTop: 8 }} />}<div style={{ display: 'flex', gap: 8, marginTop: 10 }}><button disabled={!dirty || !title.trim() || needsDestination && !draftDestinationId && !draftDestinationLabel.trim()} onClick={() => props.onUpdateTrail(trail, { title: title.trim(), category: draftCategory, destinationFeatureId: draftDestinationId || null, destinationLabel: draftDestinationLabel.trim() || null })} style={{ ...actionBtn, flex: 1, opacity: !dirty || !title.trim() || needsDestination && !draftDestinationId && !draftDestinationLabel.trim() ? 0.45 : 1 }}>Save trail</button><button onClick={() => { if (window.confirm(`Delete trail ${trail.feature.title}?`)) props.onDeleteTrail(trail); }} style={{ ...dangerActionBtn, flex: 1 }}>Delete trail</button></div></div>}
    <PhotoGrid uploads={trailUploads} contextLabel={contextLabel} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onDeleteUpload={props.onDeleteUpload} />
    <StatGrid items={[[ 'Distance', String(trail.feature.properties.dist ?? '—') ], [ 'Destination', destinationName || '—' ], [ 'Category', trailCategoryLabel(category) ], [ 'Elevation', String(trail.feature.properties.gain ?? '—') ]]} />
    <Label>Notes</Label><AddNoteCTA onOpen={props.onOpenComposer} />{trailNotes.map(n => <NoteCard key={n.id} note={n} uploads={props.uploads} contextLabel={contextLabel} canWrite={props.canWrite} onOpenPhoto={props.onOpenPhoto} onEdit={props.onEditNote} onDelete={props.onDeleteNote} onDeleteUpload={props.onDeleteUpload} />)}
  </div>;
}
function DevPicker({ boulder, canWrite, onSetDev }: { boulder: MoneyCragNode; canWrite: boolean; onSetDev: (id: string, dev: MoneyDevStatus) => void }) { const dev = boulder.feature.status as MoneyDevStatus; const meta = DEV.meta[dev] ?? DEV.meta.scouted; return <div style={{ marginBottom: 16 }}><Label>Development status</Label><div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>{DEV.order.map(k => { const mm = DEV.meta[k]; const on = dev === k; return <button disabled={!canWrite} key={k} onClick={() => onSetDev(boulder.feature.id, k)} style={{ display: 'flex', alignItems: 'center', gap: 6, border: `1px solid ${on ? mm.c : T.line2}`, background: on ? mm.bg : 'transparent', color: on ? mm.c : T.mut, borderRadius: 8, padding: '7px 10px', fontWeight: 700, fontSize: 12, cursor: canWrite ? 'pointer' : 'default' }}><span style={{ width: 7, height: 7, borderRadius: '50%', background: mm.c }} />{mm.short}</button>; })}</div><div style={{ fontSize: 11.5, color: T.mut, marginTop: 7 }}>{meta.desc}.</div></div>; }
function AddProblem({ onAdd }: { onAdd: (p: { name: string; grade: string; status: MoneyProblemStatus; stars: number; fa?: string | null; types: string[] }) => void }) { const [name, setName] = useState(''); const [grade, setGrade] = useState('V?'); const [status, setStatus] = useState<MoneyProblemStatus>('project'); const [fa, setFa] = useState(''); const [types, setTypes] = useState<string[]>([]); const toggle = (t: string) => setTypes(ts => ts.includes(t) ? ts.filter(x => x !== t) : [...ts, t]); return <div style={{ background: T.inset, border: `1px solid ${T.line2}`, borderRadius: 10, padding: 12, marginBottom: 12 }}><input value={name} onChange={e => setName(e.target.value)} placeholder="Problem name" style={inp} /><div style={{ display: 'flex', gap: 8, marginTop: 8 }}><input value={grade} onChange={e => setGrade(e.target.value)} style={{ ...inp, width: 64, fontFamily: T.mono }} /><select value={status} onChange={e => setStatus(e.target.value as MoneyProblemStatus)} style={{ ...inp, flex: 1 }}><option value="project">project</option><option value="sent">sent</option><option value="established">established</option></select></div><input value={fa} onChange={e => setFa(e.target.value)} placeholder="First ascent — optional" style={{ ...inp, marginTop: 8 }} /><Label>Style</Label><div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>{PTYPES.map(t => <button key={t} onClick={() => toggle(t)} style={{ border: `1px solid ${types.includes(t) ? T.accent : T.line2}`, background: types.includes(t) ? T.accentSoft : 'transparent', color: types.includes(t) ? T.accent : T.mut, borderRadius: 20, padding: '5px 10px', fontSize: 11.5, fontWeight: 600 }}>{t}</button>)}</div><button disabled={!name.trim()} onClick={() => onAdd({ name: name.trim(), grade, status, stars: 1, fa: fa.trim() || null, types })} style={{ width: '100%', border: 'none', borderRadius: 9, padding: 11, marginTop: 12, background: name.trim() ? T.accent : T.line2, color: name.trim() ? T.onAccent : T.faint, fontWeight: 800 }}>Add problem</button></div>; }
function ProblemRow({ p, i }: { p: MoneyCragNode; i: number }) { const m = problemMeta(p.feature); return <div style={{ padding: '10px 12px', borderTop: i ? `1px solid ${T.line}` : 'none' }}><div style={{ display: 'flex', alignItems: 'center', gap: 10 }}><span style={{ fontFamily: T.mono, fontSize: 12.5, fontWeight: 700, color: T.accent, width: 38 }}>{m.grade}</span><span style={{ flex: 1, fontSize: 13.5, fontWeight: 600, color: T.ink }}>{p.feature.title}</span><Stars n={m.stars} /><Badge status={m.status} /></div></div>; }
function NoteCard({ note, uploads, contextLabel, canWrite, onOpenPhoto, onEdit, onDelete, onDeleteUpload }: { note: MoneyNote; uploads: MoneyUpload[]; contextLabel?: string; canWrite: boolean; onOpenPhoto: OpenPhoto; onEdit: (note: MoneyNote) => void; onDelete: (note: MoneyNote) => void; onDeleteUpload: (upload: MoneyUpload) => void }) { const noteUploads = useMemo(() => uploadsForNoteBlocks(uploads, note), [note, uploads]); return <div style={{ background: T.inset, border: `1px solid ${T.line}`, borderRadius: 10, padding: '12px 14px', marginBottom: 8 }}><div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 8 }}><span style={{ width: 22, height: 22, borderRadius: '50%', background: T.av, color: '#fff', fontSize: 9, fontWeight: 700, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>MC</span><span style={{ fontSize: 12.5, fontWeight: 700, color: T.ink }}>Team</span><span style={{ marginLeft: 'auto', fontFamily: T.mono, fontSize: 10.5, color: T.mut }}>{new Date(note.created_at).toLocaleDateString()}</span>{canWrite && <><button aria-label="Edit note" onClick={() => onEdit(note)} style={miniBtn}>Edit</button><button aria-label="Delete note" onClick={() => { if (window.confirm('Delete this note?')) onDelete(note); }} style={{ ...miniBtn, color: '#E6A299' }}>Delete</button></>}</div>{note.body && <p style={p}>{note.body}</p>}{noteUploads.length > 0 && <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(96px,1fr))', gap: 8, marginBottom: 10 }}>{noteUploads.map(upload => <UploadPhotoButton key={upload.id} upload={upload} ratio="1 / 1" canDelete={canWrite} onDelete={onDeleteUpload} onOpen={() => onOpenPhoto(upload, { contextLabel, noteBody: note.body })} />)}</div>}{(note.tags ?? []).length > 0 && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 5 }}>{(note.tags ?? []).map(t => <span key={t} style={{ fontSize: 10.5, color: T.mut, background: T.surf2, border: `1px solid ${T.line}`, borderRadius: 20, padding: '2px 8px' }}>#{t}</span>)}</div>}</div>; }
const p: React.CSSProperties = { margin: '0 0 14px', fontSize: 13, lineHeight: 1.55, color: '#D9CBBD' };
const scroll: React.CSSProperties = { flex: 1, overflowY: 'auto', minHeight: 0, padding: '16px 20px' };
const inp: React.CSSProperties = { width: '100%', background: T.surf2, border: `1px solid ${T.line}`, borderRadius: 7, padding: '9px 10px', color: T.ink, fontFamily: T.font, fontSize: 13, outline: 'none', minHeight: 40 };
const miniBtn: React.CSSProperties = { border: `1px solid ${T.line2}`, background: T.inset, color: T.mut, borderRadius: 6, cursor: 'pointer', fontSize: 10.5, padding: '3px 6px', fontWeight: 800 };
const actionBtn: React.CSSProperties = { border: `1px solid ${T.line2}`, borderRadius: 10, padding: 12, background: T.surf, color: T.ink, fontWeight: 800, cursor: 'pointer', textAlign: 'left' };
const dangerActionBtn: React.CSSProperties = { border: 'none', borderRadius: 10, padding: 12, background: '#B65B4D', color: '#fff', fontWeight: 800, cursor: 'pointer', textAlign: 'left' };
function Label({ children }: { children: React.ReactNode }) { return <div style={{ fontFamily: T.mono, fontSize: 11, letterSpacing: 0.6, color: T.mut, textTransform: 'uppercase', margin: '4px 0 8px' }}>{children}</div>; }
function StatGrid({ items }: { items: Array<[string, string | number]> }) { return <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, marginBottom: 16 }}>{items.map(([l, v]) => <div key={l} style={{ background: T.inset, border: `1px solid ${T.line}`, borderRadius: 10, padding: '11px 13px' }}><div style={{ fontSize: 23, fontWeight: 800, color: T.ink }}>{v}</div><div style={{ fontFamily: T.mono, fontSize: 10.5, color: T.mut, textTransform: 'uppercase' }}>{l}</div></div>)}</div>; }
function DevBar({ st }: { st: ReturnType<typeof stats> }) { return <div style={{ marginBottom: 16 }}><Label>Boulder development</Label><div style={{ display: 'flex', height: 8, borderRadius: 4, overflow: 'hidden', background: T.inset, border: `1px solid ${T.line}` }}>{DEV.order.map(k => st.dev[k] ? <div key={k} style={{ flex: st.dev[k], background: DEV.meta[k].c }} /> : null)}</div></div>; }
function DevBadge({ dev }: { dev: MoneyDevStatus }) { const m = DEV.meta[dev] ?? DEV.meta.scouted; return <span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, color: m.c, background: m.bg, padding: '2px 7px', borderRadius: 5 }}>{m.short}</span>; }
function BigButton({ icon, title, sub, onClick, danger }: { icon: React.ReactNode; title: string; sub: string; onClick: () => void; danger?: boolean }) { return <button onClick={onClick} style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'flex-start', gap: 3, border: `1px solid ${danger ? '#8F4E45' : T.accentDim}`, background: danger ? 'rgba(143,78,69,0.14)' : T.accentSoft, color: danger ? '#E6A299' : T.accent, borderRadius: 11, padding: '11px 12px', cursor: 'pointer', textAlign: 'left' }}><span style={{ display: 'flex', alignItems: 'center', gap: 7, fontWeight: 700, fontSize: 13.5 }}>{icon}{title}</span><span style={{ fontSize: 10.5, color: T.mut }}>{sub}</span></button>; }
function SmallButton({ children, onClick }: { children: React.ReactNode; onClick?: () => void }) { return <button onClick={onClick} style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7, border: `1px solid ${T.accentDim}`, background: T.accentSoft, color: T.accent, borderRadius: 10, padding: 11, fontWeight: 700, fontSize: 13, cursor: 'pointer' }}>{children}</button>; }
function AddNoteCTA({ onOpen }: { onOpen: (kind?: 'photo' | 'sketch' | 'file' | null) => void }) { return <div style={{ display: 'flex', gap: 8, marginBottom: 12 }}><SmallButton onClick={() => onOpen(null)}><FileText size={15} />Write a note</SmallButton><SmallButton onClick={() => onOpen('photo')}><Camera size={15} /></SmallButton></div>; }
function List({ children }: { children: React.ReactNode }) { return <div style={{ border: `1px solid ${T.line}`, borderRadius: 10, overflow: 'hidden', borderTopWidth: 0, marginBottom: 16 }}><div style={{ borderTop: `1px solid ${T.line}` }} />{children}</div>; }
function Row({ title, sub, right, onClick }: { title: string; sub?: string; right?: React.ReactNode; onClick: () => void }) { return <div onClick={onClick} style={{ display: 'flex', alignItems: 'center', gap: 11, padding: '10px 12px', borderTop: `1px solid ${T.line}`, cursor: 'pointer', background: T.surf }}><span style={{ width: 9, height: 9, borderRadius: 2, background: T.accent, transform: 'rotate(45deg)' }} /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 13.5, fontWeight: 600, color: T.ink }}>{title}</div>{sub && <div style={{ fontFamily: T.mono, fontSize: 10.5, color: T.mut }}>{sub}</div>}</div>{right}</div>; }
function Empty({ children }: { children: React.ReactNode }) { return <div style={{ textAlign: 'center', color: T.faint, fontSize: 12.5, padding: '16px 0' }}>{children}</div>; }
function Stars({ n }: { n: number }) { return <span style={{ display: 'inline-flex', gap: 1 }}>{[0, 1, 2].map(i => <Star key={i} size={11} fill={i < n ? T.accent : 'none'} stroke={i < n ? T.accent : T.line2} />)}</span>; }
function Badge({ status }: { status: MoneyProblemStatus }) { const c = status === 'sent' ? T.blue : status === 'project' ? T.accent : T.mut; return <span style={{ fontFamily: T.mono, fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: c, background: `${c}22`, padding: '2px 7px', borderRadius: 5 }}>{status}</span>; }
function Stripe({ label, ratio }: { label: string; ratio?: string }) { return <div style={{ position: 'relative', width: '100%', aspectRatio: ratio || '4 / 3', backgroundColor: T.map.slot, backgroundImage: `repeating-linear-gradient(45deg, ${T.map.slotStripe} 0 1px, transparent 1px 9px)`, display: 'flex', alignItems: 'flex-end', overflow: 'hidden', borderRadius: 8 }}><span style={{ fontFamily: T.mono, fontSize: 10, color: T.map.slotText, padding: '5px 7px' }}>{label}</span></div>; }
function PhotoGrid({ uploads, ratio = '1 / 1', contextLabel, canWrite, onOpenPhoto, onDeleteUpload }: { uploads: MoneyUpload[]; ratio?: string; contextLabel?: string; canWrite?: boolean; onOpenPhoto: OpenPhoto; onDeleteUpload: (upload: MoneyUpload) => void }) { if (uploads.length === 0) return <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, margin: '14px 0' }}>{['topo photo', 'the lines'].map(l => <Stripe key={l} label={l} ratio={ratio} />)}</div>; return <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8, margin: '14px 0' }}>{uploads.map(upload => <UploadPhotoButton key={upload.id} upload={upload} ratio={ratio} canDelete={Boolean(canWrite)} onDelete={onDeleteUpload} onOpen={() => onOpenPhoto(upload, { contextLabel })} />)}</div>; }
function uploadsForTarget(uploads: MoneyUpload[], notes: MoneyNote[], featureId: string): MoneyUpload[] { const ids = new Set(notes.flatMap(note => (note.blocks ?? []).map(block => block.upload_id).filter((id): id is string => Boolean(id)))); return uploads.filter(upload => upload.feature_id === featureId || ids.has(upload.id)); }
function uploadsForNoteBlocks(uploads: MoneyUpload[], note: MoneyNote): MoneyUpload[] { const ids = new Set((note.blocks ?? []).map(block => block.upload_id).filter((id): id is string => Boolean(id))); return uploads.filter(upload => ids.has(upload.id)); }
function normalizeTrailCategory(value: unknown): MoneyTrailCategory { return value === 'approach' || value === 'trail_to_area' || value === 'trail_to_destination' ? value : 'connector'; }
function trailCategoryLabel(category: MoneyTrailCategory): string { return trailCategoryOptions.find(option => option.value === category)?.label ?? 'Connector'; }
